# Generated by Django 2.2.11 on 2020-03-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Author')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Genre')),
            ],
            options={
                'db_table': 'Book',
                'verbose_name': 'Книги',
            },
        ),
    ]
