# Generated by Django 2.2.11 on 2020-03-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='bookshop.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите имя автора', max_length=150, verbose_name='Имя'),
        ),
    ]
